[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ct-phrase-retrieval"
version = "0.0.1"
description = "Phrase-Grounded Retrieval Panel for CT (DeepLesion)"
requires-python = ">=3.10"
dependencies = []
