seed: 42

paths:
  data_root: "/kaggle/input/nih-deeplesion-subset"
  csv_name: "DL_info.csv"

results:
  dir: "/kaggle/working/results/kaggle_v1"

data:
  max_samples: 5000    

preprocess:
  ct_windows:
    - [-600, 1500]
    - [40, 400]
    - [400, 1500]
  size: 224
  clip_norm: true

encoder:
  name: "ViT-B-16"
  pretrained: "openai"
  freeze: true

index:
  kind: "flat"
  metric: "ip"

phrases:
  set:
    - "liver lesion"
    - "renal mass"
    - "splenic lesion"
    - "lung nodule"
    - "enlarged lymph node"
    - "bone lesion"


viz:
  panel_rows: 3
  panel_cols: 3
  gif_seconds: 15
  cam_alpha: 0.5

batch: 64

logging:
  level: "INFO"

notes: |
  Baseline OpenCLIP ViT-B/16 on Kaggle DeepLesion subset.
  CT 3-window → CLIP norm; FAISS Flat IP; saliency overlay.
